# Generated by Django 6.1.1 on 2026-09-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('biomarker_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('gene', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Biomarker',
                'verbose_name_plural': 'Biomarkers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('intervention_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('pmid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True, default='')),
                ('journal', models.CharField(blank=True, default='', max_length=255)),
                ('publication_date', models.CharField(blank=True, default='', max_length=100)),
                ('doi', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('biomarkers', models.ManyToManyField(blank=True, related_name='publications', to='core.biomarker')),
                ('diseases', models.ManyToManyField(blank=True, related_name='publications', to='core.disease')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('nct_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.TextField()),
                ('phase', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('biomarkers', models.ManyToManyField(blank=True, related_name='trials', to='core.biomarker')),
                ('diseases', models.ManyToManyField(blank=True, related_name='trials', to='core.disease')),
                ('interventions', models.ManyToManyField(blank=True, related_name='trials', to='core.intervention')),
            ],
            options={
                'verbose_name': 'Trial',
                'verbose_name_plural': 'Trials',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PublicationTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('relation', models.CharField(choices=[('DERIVED_FROM_TRIAL', 'DERIVED_FROM_TRIAL'), ('BACKGROUND_FOR_TRIAL', 'BACKGROUND_FOR_TRIAL'), ('REPORTS_TRIAL_RESULT', 'REPORTS_TRIAL_RESULT'), ('SUPPORTS_MECHANISM', 'SUPPORTS_MECHANISM'), ('RELATED', 'RELATED')], db_index=True, default='RELATED', max_length=64)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_trials', to='core.publication')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_trials', to='core.trial')),
            ],
            options={
                'verbose_name': 'Publication Trial Link',
                'verbose_name_plural': 'Publication Trial Links',
                'ordering': ['-created'],
                'unique_together': {('publication', 'trial', 'relation')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='trials',
            field=models.ManyToManyField(blank=True, related_name='publications', through='core.PublicationTrial', to='core.trial'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('observation_type', models.CharField(db_index=True, max_length=100)),
                ('summary', models.TextField()),
                ('biomarker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='core.biomarker')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='core.disease')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.publication')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.trial')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('claim_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('FOUND', 'FOUND'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED')], db_index=True, default='FOUND', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('patient_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('provider_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.disease')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.intervention')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.trial')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-created'],
            },
        ),
    ]
