# Generated by Django 6.1.1 on 2026-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='acronym',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trial',
            name='arms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='collaborators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='completion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='completion_date_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trial',
            name='conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='contacts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trial',
            name='design_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trial',
            name='detailed_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trial',
            name='eligibility_criteria',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trial',
            name='enrollment',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='enrollment_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trial',
            name='first_posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='has_results',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='trial',
            name='healthy_volunteers',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='interventions_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='last_update_posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='lead_sponsor',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trial',
            name='locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='maximum_age',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trial',
            name='minimum_age',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trial',
            name='official_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trial',
            name='org_study_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trial',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trial',
            name='outcomes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trial',
            name='primary_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='raw',
            field=models.JSONField(blank=True, default=dict, help_text='Raw API response payload from ClinicalTrials.gov'),
        ),
        migrations.AddField(
            model_name='trial',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trial',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trial',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='start_date_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='trial',
            name='study_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
