# Generated by Django 6.1.1 on 2026-09-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trial_acronym_trial_arms_trial_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_str',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='chemicals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publication',
            name='citation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='databanks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publication',
            name='first_author',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='grants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publication',
            name='history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publication',
            name='interventions',
            field=models.ManyToManyField(blank=True, related_name='publications', to='core.intervention'),
        ),
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='publication',
            name='mesh_terms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publication',
            name='pmc',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_types',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='publication',
            name='pubmed_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publication',
            name='raw',
            field=models.JSONField(blank=True, default=dict, help_text='Raw payload from PubMed/metapub/Entrez'),
        ),
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
