# Generated by Django 5.2.17 on 2026-09-30 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_publication_authors_publication_authors_str_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("body", models.TextField()),
                ("section", models.CharField(max_length=64)),
                ("sequ", models.PositiveIntegerField()),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.publication",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.trial",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("publication__isnull", False), ("trial__isnull", True)
                            ),
                            models.Q(
                                ("publication__isnull", True), ("trial__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="chunk_exactly_one_owner",
                    )
                ],
            },
        ),
    ]
