# Generated by Django 6.1.1 on 2026-09-30 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField()),
                ('label', models.JSONField(default=list)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('method', models.JSONField(default=list)),
                ('model_name', models.JSONField(default=list)),
                ('links', models.JSONField(default=list)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ners', to='core.chunk')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ners', to='core.publication')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ners', to='core.trial')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('publication__isnull', False), ('trial__isnull', True)), models.Q(('publication__isnull', True), ('trial__isnull', False)), _connector='OR'), name='ner_exactly_one_owner')],
            },
        ),
    ]
