# Generated by Django 6.1.1 on 2026-09-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtrial',
            name='relation',
            field=models.CharField(choices=[('DERIVED', 'DERIVED'), ('DERIVED_FROM_TRIAL', 'DERIVED_FROM_TRIAL'), ('BACKGROUND_FOR_TRIAL', 'BACKGROUND_FOR_TRIAL'), ('REPORTS_TRIAL_RESULT', 'REPORTS_TRIAL_RESULT'), ('SUPPORTS_MECHANISM', 'SUPPORTS_MECHANISM'), ('RELATED', 'RELATED')], db_index=True, default='RELATED', max_length=64),
        ),
    ]
