# Generated by Django 6.1.1 on 2026-09-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
