# Generated by Django 6.1.1 on 2026-10-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_claims_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTrails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('status_from', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=8)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=8)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_trails', to='core.publication')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_trails', to='core.trial')),
            ],
            options={
                'verbose_name': 'Claim Trail',
                'verbose_name_plural': 'Claim Trails',
                'ordering': ['-created', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('trial__isnull', False), ('publication__isnull', False), _connector='OR'), name='claim_trails_has_source')],
            },
        ),
    ]
