# Generated by Django 6.1.1 on 2026-10-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_claimtrails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('query', models.CharField(max_length=500, unique=True)),
                ('ingest_trials_count', models.PositiveIntegerField(default=0)),
                ('ingest_publications_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Focus',
                'verbose_name_plural': 'Focuses',
                'ordering': ['-created', '-id'],
            },
        ),
    ]
