# Generated by Django 6.1.1 on 2026-10-02 20:55

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


def backfill_trail_entities(apps, schema_editor):
    """Fill array columns from the claim snapshot stored in meta."""
    ClaimTrails = apps.get_model('core', 'ClaimTrails')
    for row in ClaimTrails.objects.iterator():
        claim = (row.meta or {}).get('claim') or {}
        diseases = [pk for pk in (claim.get('diseases') or []) if isinstance(pk, int)]
        interventions = [pk for pk in (claim.get('interventions') or []) if isinstance(pk, int)]
        if diseases != list(row.diseases or []) or interventions != list(row.interventions or []):
            row.diseases = diseases
            row.interventions = interventions
            row.save(update_fields=['diseases', 'interventions'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimtrails',
            name='diseases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='claimtrails',
            name='interventions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='claimtrails',
            index=django.contrib.postgres.indexes.GinIndex(fields=['diseases'], name='trails_diseases_gin'),
        ),
        migrations.AddIndex(
            model_name='claimtrails',
            index=django.contrib.postgres.indexes.GinIndex(fields=['interventions'], name='trails_interv_gin'),
        ),
        migrations.RunPython(backfill_trail_entities, migrations.RunPython.noop),
    ]
